import Head from 'next/head'
import { useContext, useEffect } from 'react'
import styled from 'styled-components'
import { ThemeContext } from '../utils/theme'

export default function Home() {

  const {theme, toggleTheme} = useContext(ThemeContext)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={toggleTheme}>
        DARK MODE
      </button>
    </>
  )
}
